namespace Arion.Theme.Controls
{
    public enum EIcons
    {
        Folder,
        Hand,
        AutoMode,
        SaveMode,
        Xray,
        Find,
        FindX2,
        FindX4,
        List,
        Blocks,
        Option,
        Setting,
        File,
        Download,
        Save,
        Minimize,
        PowerOff,
        User,
        Close,
        Text,
        Training,
        Rotate,
        HorizontalMirror,
        VerticalMirror,
        About,
        Reorder,
        Favorite,
        Back,
        Users,
        Pinned
    }
}